# Generated by Django 4.0.4 on 2022-07-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_items_image_alter_items_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('ultra_rare', 'Ultra rare'), ('legendary', 'Legendary')], default='common', max_length=100),
        ),
    ]
