# Generated by Django 4.0.4 on 2022-07-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_items_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('ultra_rare', 'Ultra rare'), ('legendary', 'Legendary')], default='Common', max_length=100),
        ),
    ]
