# Generated by Django 4.0.4 on 2022-07-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_items_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='rarity',
            field=models.CharField(choices=[('Common', 'Common'), ('Rare', 'Rare'), ('Ultra Rare', 'Ultra Rare'), ('Legendary', 'Legendary')], default='Common', max_length=100),
        ),
    ]
