# Generated by Django 4.0.4 on 2022-07-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_items_rarity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['price']},
        ),
    ]
